In [3]:
import time

import numpy as np
import tensorflow.compat.v2 as tf #tf2.0
tf.enable_v2_behavior()

import tensorflow_probability as tfp
tfd=tfp.distributions #多変量正規分布
tfk=tfp.math.psd_kernels #半正定値カーネル

%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [10]:
#Load Data
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

In [7]:
N=1000

In [21]:
x_train[0][10]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,  14,   1, 154, 253,
        90,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0], dtype=uint8)

In [22]:
x_train[0].shape

(28, 28)

In [23]:
x_train.shape

(60000, 28, 28)

In [24]:
y_train[0]

5

In [26]:
y_train[0].shape

()

In [25]:
y_train.shape

(60000,)

In [33]:
x_train = x_train[:N, ].astype(np.float64) / 256.
x_train.shape

(1000, 28, 28)

In [34]:
x_train[0].shape

(28, 28)

In [36]:
y_train = y_train[:N, ]
y_train[:6]

array([5, 0, 4, 1, 9, 2], dtype=uint8)

In [37]:
np.float64(1.)

1.0

In [39]:
# Create our kernel and GP distribution
EPS = np.finfo(np.float64).eps
EPS

2.220446049250313e-16

In [41]:
unconstrained_amplitude = tf.Variable(np.float64(1.), name='amplitude')
tf.math.softplus(EPS + unconstrained_amplitude)

<tf.Tensor: shape=(), dtype=float64, numpy=1.313261687518223>